name: backend
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
 shelf: ^1.4.0
 shelf_modular: ^2.0.1
 postgres: ^2.5.2
 shelf_swagger_ui: ^1.0.0+2
 bcrypt: ^1.1.3
 dart_jsonwebtoken: ^2.6.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
