// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTfA_RR6h-Qlm5VGjzR1BSof4uCOrbINY',
    appId: '1:859807707140:web:114efb11d2a835c509c551',
    messagingSenderId: '859807707140',
    projectId: 'ecoatendimento-65014',
    authDomain: 'ecoatendimento-65014.firebaseapp.com',
    storageBucket: 'ecoatendimento-65014.appspot.com',
    measurementId: 'G-9P34F4VPG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoNsQ9wAa_bwpIb1yKMqQuGoqkX0zi5DY',
    appId: '1:859807707140:android:ad1fec830b212dd009c551',
    messagingSenderId: '859807707140',
    projectId: 'ecoatendimento-65014',
    storageBucket: 'ecoatendimento-65014.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNv6xFKurs2JT99ENKXclw9FMuEUdeQac',
    appId: '1:859807707140:ios:1a7b754d1a66a8ef09c551',
    messagingSenderId: '859807707140',
    projectId: 'ecoatendimento-65014',
    storageBucket: 'ecoatendimento-65014.appspot.com',
    iosClientId: '859807707140-cluv4dufqoct0h7tk2k9iefg44tbvsc4.apps.googleusercontent.com',
    iosBundleId: 'com.arv.atendimento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNv6xFKurs2JT99ENKXclw9FMuEUdeQac',
    appId: '1:859807707140:ios:1a7b754d1a66a8ef09c551',
    messagingSenderId: '859807707140',
    projectId: 'ecoatendimento-65014',
    storageBucket: 'ecoatendimento-65014.appspot.com',
    iosClientId: '859807707140-cluv4dufqoct0h7tk2k9iefg44tbvsc4.apps.googleusercontent.com',
    iosBundleId: 'com.arv.atendimento',
  );
}
